project:
  type: manuscript

manuscript:
  article: remis.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: apa7
    classoption: [man]
    papersize: letter
    fontsize: 12pt
    linestretch: 2
    include-in-header:
      text: |
        \usepackage{csquotes}