name: Render manuscript

on:
  push:
    paths:
      - "remis.qmd"
      - "_quarto.yml"
      - "references.bib"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R basics
        run: |
          Rscript -e 'install.packages(c("rmarkdown","knitr"), repos="https://cloud.r-project.org")'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install LaTeX packages
        run: tlmgr install apa7 csquotes

      - name: Render manuscript
        run: quarto render remis.qmd

      - name: Check outputs
        run: |
          ls -lah
          test -f remis.pdf

      - name: Commit updated PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add remis.pdf
          git diff --cached --quiet || git commit -m "Update rendered PDF"
          git push
