name: Render manuscript

on:
  push:
    paths:
      - "remis.qmd"
      - "_quarto.yml"
      - "references.bib"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown","knitr"), repos="https://cloud.r-project.org")'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install LaTeX packages
        run: tlmgr install apa7 csquotes

      - name: Render project
        run: quarto render

      - name: Show rendered files
        run: find . -maxdepth 2 -type f | sort

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: rendered-manuscript
          if-no-files-found: error
          path: |
            remis.html
            remis.pdf
